### Create bakery
POST http://localhost:8080/api/bakery
Content-Type: multipart/form-data

bakeryName=Test Bakery
arrondissement=1
address=1-1-1
rating=4.5
notes=test
visitedDate=2026-08-24
favorite=true
photo=@./test.jpg
mapsUrl=https://maps.google.com
